name: server_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer:
  dart_style:
  markdown:
  more:
  postgres:
  postgres_pool:
  process_runner:
  quiver:
  shelf_proxy:
  shelf_router:
  shelf_static:

dev_dependencies:
  build_runner:
  build_test:
  faker:
  json_serializable:
  lints:
  test:
