// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// RpcClientGenerator
// **************************************************************************

// GENERATED-CODE: do not edit
// This code is generated by the rpc_builder tool

import 'dart:convert';
import 'package:http/http.dart';
import 'package:path/path.dart' as path_helper;
import 'package:server_utils/rpc_client.dart';
import 'api.dart' show News, MoveType, CmsPage;

export 'api.dart' show News, MoveType, CmsPage;

// ignore_for_file: implementation_imports
// ignore_for_file: unnecessary_string_interpolations

class NewsClient {
  final Client _client;
  final String _basePath;

  NewsClient(this._client, {required String basePath}) : _basePath = basePath;

  Future<String> simpleString() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'simple-string'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> greeting(String name) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'greeting'));
    $url = $url.replace(queryParameters: {
      'name': name,
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> greetingWithNamed(String name,
      {String? prefix, String? suffix}) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'greeting-with-named'));
    $url = $url.replace(queryParameters: {
      'name': name,
      if (prefix != null) 'prefix': prefix,
      if (suffix != null) 'suffix': suffix,
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> greetingWithRequired({required int count}) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'greeting-with-required'));
    $url = $url.replace(queryParameters: {
      'count': count.toString(),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> allTypes(
      {int? aInt,
      required int requiredInt,
      bool? aBool,
      required bool requiredBool,
      num? aNum,
      required num requiredNum,
      double? aDouble,
      required double requiredDouble,
      String? aString,
      required String requiredString,
      DateTime? aDate,
      required DateTime requiredDate}) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'all-types'));
    $url = $url.replace(queryParameters: {
      if (aInt != null) 'aInt': aInt.toString(),
      'requiredInt': requiredInt.toString(),
      if (aBool != null) 'aBool': aBool.toString(),
      'requiredBool': requiredBool.toString(),
      if (aNum != null) 'aNum': aNum.toString(),
      'requiredNum': requiredNum.toString(),
      if (aDouble != null) 'aDouble': aDouble.toString(),
      'requiredDouble': requiredDouble.toString(),
      if (aString != null) 'aString': aString,
      'requiredString': requiredString,
      if (aDate != null) 'aDate': aDate.toString(),
      'requiredDate': requiredDate.toString(),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> getList(
      List<int> ints, List<bool> bools, List<String> strings) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'get-list'));
    $url = $url.replace(queryParameters: {
      'ints': jsonEncode(ints),
      'bools': jsonEncode(bools),
      'strings': jsonEncode(strings),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> getListNullableValue(
      List<int?> ints, List<bool?> bools, List<String?> strings) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'get-list-nullable-value'));
    $url = $url.replace(queryParameters: {
      'ints': jsonEncode(ints),
      'bools': jsonEncode(bools),
      'strings': jsonEncode(strings),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> getListNullable(
      List<int?>? ints, List<bool?>? bools, List<String?>? strings) async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'get-list-nullable'));
    $url = $url.replace(queryParameters: {
      if (ints != null) 'ints': jsonEncode(ints),
      if (bools != null) 'bools': jsonEncode(bools),
      if (strings != null) 'strings': jsonEncode(strings),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> getMap(Map<String, int> ints, Map<String, bool> bools,
      Map<String, String> strings) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'get-map'));
    $url = $url.replace(queryParameters: {
      'ints': jsonEncode(ints),
      'bools': jsonEncode(bools),
      'strings': jsonEncode(strings),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> postList(
      List<int> ints, List<bool> bools, List<String> strings) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'post-list'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'ints': ints,
          'bools': bools,
          'strings': strings,
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<String> postMap(Map<String, int> ints, Map<String, bool> bools,
      Map<String, String> strings) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'post-map'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'ints': ints,
          'bools': bools,
          'strings': strings,
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }

  Future<List<News>> lastNews({int? count}) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'last-news'));
    $url = $url.replace(queryParameters: {
      if (count != null) 'count': count.toString(),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => News.fromJson(i! as Map<String, Object?>))
        .toList();
  }

  Future<News> echo(News news) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'echo'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'news': news.toJson(),
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return News.fromJson($decodedResponse! as Map<String, Object?>);
  }

  Future<List<News>> sendReceiveNewsPost(List<News> news) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'send-receive-news-post'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'news': news.map((i) => i.toJson()).toList(),
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => News.fromJson(i! as Map<String, Object?>))
        .toList();
  }

  Future<List<News>> sendReceiveNewsGet(List<News> news) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'send-receive-news-get'));
    $url = $url.replace(queryParameters: {
      'news': jsonEncode(news.map((i) => i.toJson()).toList()),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => News.fromJson(i! as Map<String, Object?>))
        .toList();
  }

  Future<Map<String, News>> sendReceiveMapNewsPost(
      Map<String, News> news) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'send-receive-map-news-post'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'news': news.map((k, v) => MapEntry(k, v.toJson())),
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as Map<String, Object?>)
        .map((k, v) => MapEntry(k, News.fromJson(v! as Map<String, Object?>)));
  }

  Future<Map<String, News>> sendReceiveMapNewsGet(
      Map<String, News> news) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'send-receive-map-news-get'));
    $url = $url.replace(queryParameters: {
      'news': jsonEncode(news.map((k, v) => MapEntry(k, v.toJson()))),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as Map<String, Object?>)
        .map((k, v) => MapEntry(k, News.fromJson(v! as Map<String, Object?>)));
  }

  Future<List<String>> getListString() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'get-list-string'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => i! as String)
        .toList();
  }

  Future<List<String>> getListStringPost() async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'get-list-string-post'));
    var $response = await _client.post($url,
        body: jsonEncode({}), headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => i! as String)
        .toList();
  }

  Future<List<bool>> getListBool() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'get-list-bool'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>).map((i) => i! as bool).toList();
  }

  Future<List<bool>> getListBoolPost() async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'get-list-bool-post'));
    var $response = await _client.post($url,
        body: jsonEncode({}), headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>).map((i) => i! as bool).toList();
  }

  Future<void> aVoid(int id) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'a-void'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'id': id,
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
  }

  Future<bool> returnBool() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'return-bool'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as bool;
  }

  Future<num> returnNum() async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'return-num'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as num;
  }

  Future<double> returnDouble() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'return-double'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as num).toDouble();
  }

  Future<int> returnInt() async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'return-int'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as num).toInt();
  }

  Future<DateTime> returnDateTime() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'return-date-time'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return DateTime.parse($decodedResponse! as String);
  }

  Future<List<DateTime>> returnListDateTime() async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'return-list-date-time'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => DateTime.parse(i! as String))
        .toList();
  }

  Future<List<DateTime>> returnFutureListDateTime() async {
    var $url = Uri.parse(path_helper.url
        .join(_basePath, 'news', 'return-future-list-date-time'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => DateTime.parse(i! as String))
        .toList();
  }

  Future<List<MoveType?>> echoEnum(MoveType type1, {MoveType? type2}) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'echo-enum'));
    $url = $url.replace(queryParameters: {
      'type1': type1.toString(),
      if (type2 != null) 'type2': type2.toString(),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => apiUtils.enumFrom(i as String?, MoveType.values))
        .toList();
  }

  Future<CmsPage<News>> getPage() async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'get-page'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return CmsPage<News>.fromJson(
      $decodedResponse! as Map<String, Object?>,
      contentReviver: (d) => News.fromJson(d! as Map<String, Object?>),
    );
  }

  Future<Map<String, CmsPage<News>>> getPagesMap() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'get-pages-map'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as Map<String, Object?>).map((k, v) => MapEntry(
        k,
        CmsPage<News>.fromJson(
          v! as Map<String, Object?>,
          contentReviver: (d) => News.fromJson(d! as Map<String, Object?>),
        )));
  }

  Future<List<CmsPage<News>>> getPagesList() async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'get-pages-list'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => CmsPage<News>.fromJson(
              i! as Map<String, Object?>,
              contentReviver: (d) => News.fromJson(d! as Map<String, Object?>),
            ))
        .toList();
  }

  Future<void> throwAnException() async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'throw-an-exception'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
  }

  Future<void> throwANotFoundException() async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'throwa-not-found-exception'));
    var $response = await _client.post($url,
        body: jsonEncode({}), headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
  }

  Future<void> throwAInvalidInputException() async {
    var $url = Uri.parse(path_helper.url
        .join(_basePath, 'news', 'throwa-invalid-input-exception'));
    var $response = await _client.post($url,
        body: jsonEncode({}), headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
  }

  Future<void> throwOtherException({required int d1}) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'throw-other-exception'));
    var $response = await _client.post($url,
        body: jsonEncode({
          'd1': d1,
        }),
        headers: {'content-type': 'application/json'});
    checkResponseSuccess($url, $response);
  }

  Future<List<int?>> echoList(List<int?> list) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'echo-list'));
    $url = $url.replace(queryParameters: {
      'list': jsonEncode(list),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as List<Object?>)
        .map((i) => (i as num?)?.toInt())
        .toList();
  }

  Future<Map<String?, int?>> echoMap(Map<String?, int?> map) async {
    var $url = Uri.parse(path_helper.url.join(_basePath, 'news', 'echo-map'));
    $url = $url.replace(queryParameters: {
      'map': jsonEncode(map),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse! as Map<String, Object?>)
        .map((k, v) => MapEntry(k, (v as num?)?.toInt()));
  }

  Future<List<int?>?> echoListNullable(List<int?>? list) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'echo-list-nullable'));
    $url = $url.replace(queryParameters: {
      if (list != null) 'list': jsonEncode(list),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse as List<Object?>?)
        ?.map((i) => (i as num?)?.toInt())
        .toList();
  }

  Future<Map<String?, int?>?> echoMapNullable(Map<String?, int?>? map) async {
    var $url =
        Uri.parse(path_helper.url.join(_basePath, 'news', 'echo-map-nullable'));
    $url = $url.replace(queryParameters: {
      if (map != null) 'map': jsonEncode(map),
    });
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return ($decodedResponse as Map<String, Object?>?)
        ?.map((k, v) => MapEntry(k, (v as num?)?.toInt()));
  }

  Future<String> withParameter(String parameter, int id, bool flag) async {
    var $url = Uri.parse(
        path_helper.url.join(_basePath, 'news', 'custom/$parameter/$id/$flag'));
    var $response = await _client.get($url);
    checkResponseSuccess($url, $response);
    var $decodedResponse = jsonDecode($response.body);
    return $decodedResponse! as String;
  }
}
